# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/ip/xvr_refclk_out/xvr_refclk_out.xci
# IP: The module: 'xvr_refclk_out' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/ip/xvr_refclk_out/synth/xvr_refclk_out_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xvr_refclk_out'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/ip/xvr_refclk_out/synth/xvr_refclk_out.xdc
# XDC: The top module name and the constraint reference have the same name: 'xvr_refclk_out'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/ip/xvr_refclk_out/xvr_refclk_out.xci
# IP: The module: 'xvr_refclk_out' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/ip/xvr_refclk_out/synth/xvr_refclk_out_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xvr_refclk_out'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/ip/xvr_refclk_out/synth/xvr_refclk_out.xdc
# XDC: The top module name and the constraint reference have the same name: 'xvr_refclk_out'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
