webtalk_init -webtalk_dir C:\\github\\hdl\\projects\\adrv9009\\zcu102\\adrv9009_zcu102.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-10-20 10:06:41" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e3459pltkk8bl25pc6os0f62b1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2904 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "68.467 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1602891154990" -context "sdk\\\\bsp/1602891154990"
webtalk_add_data -client sdk -key hwid -value "1600760857646" -context "sdk\\\\bsp/1602891154990"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1602891154990"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1602891154990"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1602891154990"
webtalk_add_data -client sdk -key uid -value "1602891157609" -context "sdk\\\\application/1602891157609"
webtalk_add_data -client sdk -key hwid -value "1600760857646" -context "sdk\\\\application/1602891157609"
webtalk_add_data -client sdk -key bspid -value "1602891154990" -context "sdk\\\\application/1602891157609"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1602891157609"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1602891157609"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1602891157609"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1602891157609"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1602891157609"
webtalk_add_data -client sdk -key Procused -value "psu_cortexa53" -context "sdk\\\\application/1602891157609"
webtalk_add_data -client sdk -key projSize -value "307.90625" -context "sdk\\\\application/1602891157609"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1603213601951"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1603213601951"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1603213601951"
webtalk_add_data -client sdk -key DebugCount -value "98" -context "sdk\\\\bsp/1603213601951"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1603213601951"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1603213601951"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1603213601951"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1603213601951"
webtalk_transmit -clientid 708061820 -regid "" -xml C:\\github\\hdl\\projects\\adrv9009\\zcu102\\adrv9009_zcu102.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\github\\hdl\\projects\\adrv9009\\zcu102\\adrv9009_zcu102.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\github\\hdl\\projects\\adrv9009\\zcu102\\adrv9009_zcu102.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
