# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/projects/common/xilinx/adi_fir_filter_constr.xdc

# XDC: imports/projects/adrv9009/zcu102/system_constr.xdc

# XDC: imports/projects/common/zcu102/zcu102_system_constr.xdc

# XDC: imports/zcu102/xvr_constraints.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_sys_ps8_0/system_sys_ps8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_ps8_0 || ORIG_REF_NAME==system_sys_ps8_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_250m_rstgen_0/system_sys_250m_rstgen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_250m_rstgen_0 || ORIG_REF_NAME==system_sys_250m_rstgen_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_500m_rstgen_0/system_sys_500m_rstgen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_500m_rstgen_0 || ORIG_REF_NAME==system_sys_500m_rstgen_0} -quiet] -quiet

# IP: bd/system/ip/system_spi0_csn_concat_0/system_spi0_csn_concat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_spi0_csn_concat_0 || ORIG_REF_NAME==system_spi0_csn_concat_0} -quiet] -quiet

# IP: bd/system/ip/system_VCC_1_0/system_VCC_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_VCC_1_0 || ORIG_REF_NAME==system_VCC_1_0} -quiet] -quiet

# IP: bd/system/ip/system_GND_1_0/system_GND_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_GND_1_0 || ORIG_REF_NAME==system_GND_1_0} -quiet] -quiet

# IP: bd/system/ip/system_spi1_csn_concat_0/system_spi1_csn_concat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_spi1_csn_concat_0 || ORIG_REF_NAME==system_spi1_csn_concat_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_sysid_0_0/system_axi_sysid_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_sysid_0_0 || ORIG_REF_NAME==system_axi_sysid_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rom_sys_0_0/system_rom_sys_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rom_sys_0_0 || ORIG_REF_NAME==system_rom_sys_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_cpu_interconnect_0/system_axi_cpu_interconnect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_cpu_interconnect_0 || ORIG_REF_NAME==system_axi_cpu_interconnect_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_concat_intc_0_0/system_sys_concat_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_concat_intc_0_0 || ORIG_REF_NAME==system_sys_concat_intc_0_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_concat_intc_1_0/system_sys_concat_intc_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_concat_intc_1_0 || ORIG_REF_NAME==system_sys_concat_intc_1_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_hp0_interconnect_0/system_axi_hp0_interconnect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_hp0_interconnect_0 || ORIG_REF_NAME==system_axi_hp0_interconnect_0} -quiet] -quiet

# Block Designs: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/bd_a17c.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_0/bd_a17c_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_1/bd_a17c_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_2/bd_a17c_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_3/bd_a17c_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_4/bd_a17c_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_5/bd_a17c_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_6/bd_a17c_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_7/bd_a17c_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_8/bd_a17c_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_9/bd_a17c_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_10/bd_a17c_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_11/bd_a17c_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_12/bd_a17c_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_13/bd_a17c_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_14/bd_a17c_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_15/bd_a17c_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_16/bd_a17c_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_17/bd_a17c_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_18/bd_a17c_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_19/bd_a17c_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_20/bd_a17c_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_21/bd_a17c_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_22/bd_a17c_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_23/bd_a17c_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_24/bd_a17c_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_25/bd_a17c_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_26/bd_a17c_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_27/bd_a17c_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_28/bd_a17c_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_29/bd_a17c_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_30/bd_a17c_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_31/bd_a17c_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_adrv9009_tx_clkgen_0/system_axi_adrv9009_tx_clkgen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_adrv9009_tx_clkgen_0 || ORIG_REF_NAME==system_axi_adrv9009_tx_clkgen_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_adrv9009_tx_xcvr_0/system_axi_adrv9009_tx_xcvr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_adrv9009_tx_xcvr_0 || ORIG_REF_NAME==system_axi_adrv9009_tx_xcvr_0} -quiet] -quiet

# IP: bd/system/ip/system_tx_axi_0/system_tx_axi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_tx_axi_0 || ORIG_REF_NAME==system_tx_axi_0} -quiet] -quiet

# IP: bd/system/ip/system_tx_0/system_tx_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_tx_0 || ORIG_REF_NAME==system_tx_0} -quiet] -quiet

# IP: bd/system/ip/system_util_adrv9009_tx_upack_0/system_util_adrv9009_tx_upack_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_adrv9009_tx_upack_0 || ORIG_REF_NAME==system_util_adrv9009_tx_upack_0} -quiet] -quiet

# IP: bd/system/ip/system_cdc_sync_active_0/system_cdc_sync_active_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_cdc_sync_active_0 || ORIG_REF_NAME==system_cdc_sync_active_0} -quiet] -quiet

# IP: bd/system/ip/system_rate_gen_0/system_rate_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rate_gen_0 || ORIG_REF_NAME==system_rate_gen_0} -quiet] -quiet

# IP: bd/system/ip/system_fir_interpolation_0_0/system_fir_interpolation_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_fir_interpolation_0_0 || ORIG_REF_NAME==system_fir_interpolation_0_0} -quiet] -quiet

# IP: bd/system/ip/system_logic_and_0_0/system_logic_and_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_logic_and_0_0 || ORIG_REF_NAME==system_logic_and_0_0} -quiet] -quiet

# IP: bd/system/ip/system_out_mux_0_0/system_out_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_out_mux_0_0 || ORIG_REF_NAME==system_out_mux_0_0} -quiet] -quiet

# IP: bd/system/ip/system_fir_interpolation_1_0/system_fir_interpolation_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_fir_interpolation_1_0 || ORIG_REF_NAME==system_fir_interpolation_1_0} -quiet] -quiet

# IP: bd/system/ip/system_logic_and_1_0/system_logic_and_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_logic_and_1_0 || ORIG_REF_NAME==system_logic_and_1_0} -quiet] -quiet

# IP: bd/system/ip/system_out_mux_1_0/system_out_mux_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_out_mux_1_0 || ORIG_REF_NAME==system_out_mux_1_0} -quiet] -quiet

# IP: bd/system/ip/system_fir_interpolation_2_0/system_fir_interpolation_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_fir_interpolation_2_0 || ORIG_REF_NAME==system_fir_interpolation_2_0} -quiet] -quiet

# IP: bd/system/ip/system_logic_and_2_0/system_logic_and_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_logic_and_2_0 || ORIG_REF_NAME==system_logic_and_2_0} -quiet] -quiet

# IP: bd/system/ip/system_out_mux_2_0/system_out_mux_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_out_mux_2_0 || ORIG_REF_NAME==system_out_mux_2_0} -quiet] -quiet

# IP: bd/system/ip/system_fir_interpolation_3_0/system_fir_interpolation_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_fir_interpolation_3_0 || ORIG_REF_NAME==system_fir_interpolation_3_0} -quiet] -quiet

# IP: bd/system/ip/system_logic_and_3_0/system_logic_and_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_logic_and_3_0 || ORIG_REF_NAME==system_logic_and_3_0} -quiet] -quiet

# IP: bd/system/ip/system_out_mux_3_0/system_out_mux_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_out_mux_3_0 || ORIG_REF_NAME==system_out_mux_3_0} -quiet] -quiet

# IP: bd/system/ip/system_GND_32_0/system_GND_32_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_GND_32_0 || ORIG_REF_NAME==system_GND_32_0} -quiet] -quiet

# IP: bd/system/ip/system_tpl_core_0/system_tpl_core_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_tpl_core_0 || ORIG_REF_NAME==system_tpl_core_0} -quiet] -quiet

# IP: bd/system/ip/system_data_concat_0/system_data_concat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_data_concat_0 || ORIG_REF_NAME==system_data_concat_0} -quiet] -quiet

# IP: bd/system/ip/system_enable_slice_0_0/system_enable_slice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_enable_slice_0_0 || ORIG_REF_NAME==system_enable_slice_0_0} -quiet] -quiet

# IP: bd/system/ip/system_valid_slice_0_0/system_valid_slice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_valid_slice_0_0 || ORIG_REF_NAME==system_valid_slice_0_0} -quiet] -quiet

# IP: bd/system/ip/system_enable_slice_1_0/system_enable_slice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_enable_slice_1_0 || ORIG_REF_NAME==system_enable_slice_1_0} -quiet] -quiet

# IP: bd/system/ip/system_valid_slice_1_0/system_valid_slice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_valid_slice_1_0 || ORIG_REF_NAME==system_valid_slice_1_0} -quiet] -quiet

# IP: bd/system/ip/system_enable_slice_2_0/system_enable_slice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_enable_slice_2_0 || ORIG_REF_NAME==system_enable_slice_2_0} -quiet] -quiet

# IP: bd/system/ip/system_valid_slice_2_0/system_valid_slice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_valid_slice_2_0 || ORIG_REF_NAME==system_valid_slice_2_0} -quiet] -quiet

# IP: bd/system/ip/system_enable_slice_3_0/system_enable_slice_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_enable_slice_3_0 || ORIG_REF_NAME==system_enable_slice_3_0} -quiet] -quiet

# IP: bd/system/ip/system_valid_slice_3_0/system_valid_slice_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_valid_slice_3_0 || ORIG_REF_NAME==system_valid_slice_3_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_adrv9009_tx_dma_0/system_axi_adrv9009_tx_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_adrv9009_tx_dma_0 || ORIG_REF_NAME==system_axi_adrv9009_tx_dma_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_adrv9009_dacfifo_0/system_axi_adrv9009_dacfifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_adrv9009_dacfifo_0 || ORIG_REF_NAME==system_axi_adrv9009_dacfifo_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_adrv9009_rx_clkgen_0/system_axi_adrv9009_rx_clkgen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_adrv9009_rx_clkgen_0 || ORIG_REF_NAME==system_axi_adrv9009_rx_clkgen_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_adrv9009_rx_xcvr_0/system_axi_adrv9009_rx_xcvr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_adrv9009_rx_xcvr_0 || ORIG_REF_NAME==system_axi_adrv9009_rx_xcvr_0} -quiet] -quiet

# IP: bd/system/ip/system_rx_axi_0/system_rx_axi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rx_axi_0 || ORIG_REF_NAME==system_rx_axi_0} -quiet] -quiet

# IP: bd/system/ip/system_rx_0/system_rx_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rx_0 || ORIG_REF_NAME==system_rx_0} -quiet] -quiet

# IP: bd/system/ip/system_util_adrv9009_rx_cpack_0/system_util_adrv9009_rx_cpack_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_adrv9009_rx_cpack_0 || ORIG_REF_NAME==system_util_adrv9009_rx_cpack_0} -quiet] -quiet

# IP: bd/system/ip/system_tpl_core_1/system_tpl_core_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_tpl_core_1 || ORIG_REF_NAME==system_tpl_core_1} -quiet] -quiet

# IP: bd/system/ip/system_data_slice_0_0/system_data_slice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_data_slice_0_0 || ORIG_REF_NAME==system_data_slice_0_0} -quiet] -quiet

# IP: bd/system/ip/system_enable_slice_0_1/system_enable_slice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_enable_slice_0_1 || ORIG_REF_NAME==system_enable_slice_0_1} -quiet] -quiet

# IP: bd/system/ip/system_valid_slice_0_1/system_valid_slice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_valid_slice_0_1 || ORIG_REF_NAME==system_valid_slice_0_1} -quiet] -quiet

# IP: bd/system/ip/system_data_slice_1_0/system_data_slice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_data_slice_1_0 || ORIG_REF_NAME==system_data_slice_1_0} -quiet] -quiet

# IP: bd/system/ip/system_enable_slice_1_1/system_enable_slice_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_enable_slice_1_1 || ORIG_REF_NAME==system_enable_slice_1_1} -quiet] -quiet

# IP: bd/system/ip/system_valid_slice_1_1/system_valid_slice_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_valid_slice_1_1 || ORIG_REF_NAME==system_valid_slice_1_1} -quiet] -quiet

# IP: bd/system/ip/system_data_slice_2_0/system_data_slice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_data_slice_2_0 || ORIG_REF_NAME==system_data_slice_2_0} -quiet] -quiet

# IP: bd/system/ip/system_enable_slice_2_1/system_enable_slice_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_enable_slice_2_1 || ORIG_REF_NAME==system_enable_slice_2_1} -quiet] -quiet

# IP: bd/system/ip/system_valid_slice_2_1/system_valid_slice_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_valid_slice_2_1 || ORIG_REF_NAME==system_valid_slice_2_1} -quiet] -quiet

# IP: bd/system/ip/system_data_slice_3_0/system_data_slice_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_data_slice_3_0 || ORIG_REF_NAME==system_data_slice_3_0} -quiet] -quiet

# IP: bd/system/ip/system_enable_slice_3_1/system_enable_slice_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_enable_slice_3_1 || ORIG_REF_NAME==system_enable_slice_3_1} -quiet] -quiet

# IP: bd/system/ip/system_valid_slice_3_1/system_valid_slice_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_valid_slice_3_1 || ORIG_REF_NAME==system_valid_slice_3_1} -quiet] -quiet

# IP: bd/system/ip/system_cdc_sync_active_1/system_cdc_sync_active_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_cdc_sync_active_1 || ORIG_REF_NAME==system_cdc_sync_active_1} -quiet] -quiet

# IP: bd/system/ip/system_fir_decimation_0_0/system_fir_decimation_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_fir_decimation_0_0 || ORIG_REF_NAME==system_fir_decimation_0_0} -quiet] -quiet

# IP: bd/system/ip/system_out_mux_0_1/system_out_mux_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_out_mux_0_1 || ORIG_REF_NAME==system_out_mux_0_1} -quiet] -quiet

# IP: bd/system/ip/system_fir_decimation_1_0/system_fir_decimation_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_fir_decimation_1_0 || ORIG_REF_NAME==system_fir_decimation_1_0} -quiet] -quiet

# IP: bd/system/ip/system_out_mux_1_1/system_out_mux_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_out_mux_1_1 || ORIG_REF_NAME==system_out_mux_1_1} -quiet] -quiet

# IP: bd/system/ip/system_fir_decimation_2_0/system_fir_decimation_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_fir_decimation_2_0 || ORIG_REF_NAME==system_fir_decimation_2_0} -quiet] -quiet

# IP: bd/system/ip/system_out_mux_2_1/system_out_mux_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_out_mux_2_1 || ORIG_REF_NAME==system_out_mux_2_1} -quiet] -quiet

# IP: bd/system/ip/system_fir_decimation_3_0/system_fir_decimation_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_fir_decimation_3_0 || ORIG_REF_NAME==system_fir_decimation_3_0} -quiet] -quiet

# IP: bd/system/ip/system_out_mux_3_1/system_out_mux_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_out_mux_3_1 || ORIG_REF_NAME==system_out_mux_3_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_adrv9009_rx_dma_0/system_axi_adrv9009_rx_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_adrv9009_rx_dma_0 || ORIG_REF_NAME==system_axi_adrv9009_rx_dma_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_adrv9009_rx_os_clkgen_0/system_axi_adrv9009_rx_os_clkgen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_adrv9009_rx_os_clkgen_0 || ORIG_REF_NAME==system_axi_adrv9009_rx_os_clkgen_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_adrv9009_rx_os_xcvr_0/system_axi_adrv9009_rx_os_xcvr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_adrv9009_rx_os_xcvr_0 || ORIG_REF_NAME==system_axi_adrv9009_rx_os_xcvr_0} -quiet] -quiet

# IP: bd/system/ip/system_rx_axi_1/system_rx_axi_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rx_axi_1 || ORIG_REF_NAME==system_rx_axi_1} -quiet] -quiet

# IP: bd/system/ip/system_rx_1/system_rx_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rx_1 || ORIG_REF_NAME==system_rx_1} -quiet] -quiet

# IP: bd/system/ip/system_util_adrv9009_rx_os_cpack_0/system_util_adrv9009_rx_os_cpack_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_adrv9009_rx_os_cpack_0 || ORIG_REF_NAME==system_util_adrv9009_rx_os_cpack_0} -quiet] -quiet

# IP: bd/system/ip/system_tpl_core_2/system_tpl_core_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_tpl_core_2 || ORIG_REF_NAME==system_tpl_core_2} -quiet] -quiet

# IP: bd/system/ip/system_data_slice_0_1/system_data_slice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_data_slice_0_1 || ORIG_REF_NAME==system_data_slice_0_1} -quiet] -quiet

# IP: bd/system/ip/system_enable_slice_0_2/system_enable_slice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_enable_slice_0_2 || ORIG_REF_NAME==system_enable_slice_0_2} -quiet] -quiet

# IP: bd/system/ip/system_valid_slice_0_2/system_valid_slice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_valid_slice_0_2 || ORIG_REF_NAME==system_valid_slice_0_2} -quiet] -quiet

# IP: bd/system/ip/system_data_slice_1_1/system_data_slice_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_data_slice_1_1 || ORIG_REF_NAME==system_data_slice_1_1} -quiet] -quiet

# IP: bd/system/ip/system_enable_slice_1_2/system_enable_slice_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_enable_slice_1_2 || ORIG_REF_NAME==system_enable_slice_1_2} -quiet] -quiet

# IP: bd/system/ip/system_valid_slice_1_2/system_valid_slice_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_valid_slice_1_2 || ORIG_REF_NAME==system_valid_slice_1_2} -quiet] -quiet

# IP: bd/system/ip/system_data_slice_2_1/system_data_slice_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_data_slice_2_1 || ORIG_REF_NAME==system_data_slice_2_1} -quiet] -quiet

# IP: bd/system/ip/system_enable_slice_2_2/system_enable_slice_2_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_enable_slice_2_2 || ORIG_REF_NAME==system_enable_slice_2_2} -quiet] -quiet

# IP: bd/system/ip/system_valid_slice_2_2/system_valid_slice_2_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_valid_slice_2_2 || ORIG_REF_NAME==system_valid_slice_2_2} -quiet] -quiet

# IP: bd/system/ip/system_data_slice_3_1/system_data_slice_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_data_slice_3_1 || ORIG_REF_NAME==system_data_slice_3_1} -quiet] -quiet

# IP: bd/system/ip/system_enable_slice_3_2/system_enable_slice_3_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_enable_slice_3_2 || ORIG_REF_NAME==system_enable_slice_3_2} -quiet] -quiet

# IP: bd/system/ip/system_valid_slice_3_2/system_valid_slice_3_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_valid_slice_3_2 || ORIG_REF_NAME==system_valid_slice_3_2} -quiet] -quiet

# IP: bd/system/ip/system_axi_adrv9009_rx_os_dma_0/system_axi_adrv9009_rx_os_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_adrv9009_rx_os_dma_0 || ORIG_REF_NAME==system_axi_adrv9009_rx_os_dma_0} -quiet] -quiet

# IP: bd/system/ip/system_util_adrv9009_xcvr_0/system_util_adrv9009_xcvr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_adrv9009_xcvr_0 || ORIG_REF_NAME==system_util_adrv9009_xcvr_0} -quiet] -quiet

# IP: bd/system/ip/system_adrv9009_tx_device_clk_rstgen_0/system_adrv9009_tx_device_clk_rstgen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_adrv9009_tx_device_clk_rstgen_0 || ORIG_REF_NAME==system_adrv9009_tx_device_clk_rstgen_0} -quiet] -quiet

# IP: bd/system/ip/system_adrv9009_rx_device_clk_rstgen_0/system_adrv9009_rx_device_clk_rstgen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_adrv9009_rx_device_clk_rstgen_0 || ORIG_REF_NAME==system_adrv9009_rx_device_clk_rstgen_0} -quiet] -quiet

# IP: bd/system/ip/system_adrv9009_rx_os_device_clk_rstgen_0/system_adrv9009_rx_os_device_clk_rstgen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_adrv9009_rx_os_device_clk_rstgen_0 || ORIG_REF_NAME==system_adrv9009_rx_os_device_clk_rstgen_0} -quiet] -quiet

# IP: bd/system/ip/system_logic_or_0/system_logic_or_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_logic_or_0 || ORIG_REF_NAME==system_logic_or_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_hp1_interconnect_0/system_axi_hp1_interconnect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_hp1_interconnect_0 || ORIG_REF_NAME==system_axi_hp1_interconnect_0} -quiet] -quiet

# Block Designs: bd/system/ip/system_axi_hp1_interconnect_0/bd_0/bd_31bd.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_0/bd_31bd_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_1/bd_31bd_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_2/bd_31bd_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_3/bd_31bd_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_4/bd_31bd_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_5/bd_31bd_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_6/bd_31bd_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_7/bd_31bd_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_8/bd_31bd_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_9/bd_31bd_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_10/bd_31bd_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp2_interconnect_0/system_axi_hp2_interconnect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_hp2_interconnect_0 || ORIG_REF_NAME==system_axi_hp2_interconnect_0} -quiet] -quiet

# Block Designs: bd/system/ip/system_axi_hp2_interconnect_0/bd_0/bd_c0fd.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_0/bd_c0fd_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_1/bd_c0fd_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_2/bd_c0fd_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_3/bd_c0fd_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_4/bd_c0fd_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_5/bd_c0fd_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_6/bd_c0fd_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_7/bd_c0fd_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_8/bd_c0fd_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_9/bd_c0fd_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_10/bd_c0fd_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp3_interconnect_0/system_axi_hp3_interconnect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_hp3_interconnect_0 || ORIG_REF_NAME==system_axi_hp3_interconnect_0} -quiet] -quiet

# Block Designs: bd/system/ip/system_axi_hp3_interconnect_0/bd_0/bd_503c.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp3_interconnect_0/bd_0/ip/ip_0/bd_503c_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp3_interconnect_0/bd_0/ip/ip_1/bd_503c_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp3_interconnect_0/bd_0/ip/ip_2/bd_503c_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp3_interconnect_0/bd_0/ip/ip_3/bd_503c_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp3_interconnect_0/bd_0/ip/ip_4/bd_503c_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp3_interconnect_0/bd_0/ip/ip_5/bd_503c_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp3_interconnect_0/bd_0/ip/ip_6/bd_503c_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp3_interconnect_0/bd_0/ip/ip_7/bd_503c_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp3_interconnect_0/bd_0/ip/ip_8/bd_503c_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp3_interconnect_0/bd_0/ip/ip_9/bd_503c_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_xbar_1/system_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_1 || ORIG_REF_NAME==system_xbar_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_0/system_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_0 || ORIG_REF_NAME==system_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/system/ip/system_jtag_axi_0_0/system_jtag_axi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_jtag_axi_0_0 || ORIG_REF_NAME==system_jtag_axi_0_0} -quiet] -quiet

# IP: bd/system/ip/system_tier2_xbar_0_0/system_tier2_xbar_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_tier2_xbar_0_0 || ORIG_REF_NAME==system_tier2_xbar_0_0} -quiet] -quiet

# IP: bd/system/ip/system_tier2_xbar_1_0/system_tier2_xbar_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_tier2_xbar_1_0 || ORIG_REF_NAME==system_tier2_xbar_1_0} -quiet] -quiet

# IP: bd/system/ip/system_tier2_xbar_2_0/system_tier2_xbar_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_tier2_xbar_2_0 || ORIG_REF_NAME==system_tier2_xbar_2_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_1/system_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_1 || ORIG_REF_NAME==system_auto_pc_1} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# IP: bd/system/ip/system_s00_mmu_0/system_s00_mmu_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_s00_mmu_0 || ORIG_REF_NAME==system_s00_mmu_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_2/system_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_2 || ORIG_REF_NAME==system_auto_pc_2} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_3/system_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_3 || ORIG_REF_NAME==system_auto_pc_3} -quiet] -quiet

# IP: bd/system/ip/system_s01_mmu_0/system_s01_mmu_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_s01_mmu_0 || ORIG_REF_NAME==system_s01_mmu_0} -quiet] -quiet

# XDC: bd/system/ip/system_sys_ps8_0/system_sys_ps8_0_ooc.xdc

# XDC: bd/system/ip/system_sys_ps8_0/system_sys_ps8_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_ps8_0 || ORIG_REF_NAME==system_sys_ps8_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_sys_250m_rstgen_0/system_sys_250m_rstgen_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_250m_rstgen_0 || ORIG_REF_NAME==system_sys_250m_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_sys_250m_rstgen_0/system_sys_250m_rstgen_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_250m_rstgen_0 || ORIG_REF_NAME==system_sys_250m_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_sys_500m_rstgen_0/system_sys_500m_rstgen_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_500m_rstgen_0 || ORIG_REF_NAME==system_sys_500m_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_sys_500m_rstgen_0/system_sys_500m_rstgen_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_500m_rstgen_0 || ORIG_REF_NAME==system_sys_500m_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_hp0_interconnect_0/ooc.xdc

# XDC: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_1/bd_a17c_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_1/bd_a17c_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_2/bd_a17c_arsw_0_ooc.xdc

# XDC: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_3/bd_a17c_rsw_0_ooc.xdc

# XDC: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_4/bd_a17c_awsw_0_ooc.xdc

# XDC: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_5/bd_a17c_wsw_0_ooc.xdc

# XDC: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_6/bd_a17c_bsw_0_ooc.xdc

# XDC: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_10/bd_a17c_s00a2s_0_ooc.xdc

# XDC: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_11/bd_a17c_sarn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_12/bd_a17c_srn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_13/bd_a17c_sawn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_14/bd_a17c_swn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_15/bd_a17c_sbn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_19/bd_a17c_s01a2s_0_ooc.xdc

# XDC: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_20/bd_a17c_sarn_1_ooc.xdc

# XDC: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_21/bd_a17c_srn_1_ooc.xdc

# XDC: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_22/bd_a17c_sawn_1_ooc.xdc

# XDC: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_23/bd_a17c_swn_1_ooc.xdc

# XDC: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_24/bd_a17c_sbn_1_ooc.xdc

# XDC: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_25/bd_a17c_m00s2a_0_ooc.xdc

# XDC: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_26/bd_a17c_m00arn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_27/bd_a17c_m00rn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_28/bd_a17c_m00awn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_29/bd_a17c_m00wn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_30/bd_a17c_m00bn_0_ooc.xdc

# XDC: bd/system/xilinx/common/up_clock_mon_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_tx_axi_0 || ORIG_REF_NAME==system_tx_axi_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_tx_axi_0/system_tx_axi_0_ooc.xdc

# XDC: bd/system/ip/system_tx_axi_0/axi_jesd204_tx_constr.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_tx_axi_0 || ORIG_REF_NAME==system_tx_axi_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_tx_0/system_tx_0_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_tx_0 || ORIG_REF_NAME==system_tx_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_fir_interpolation_0_0/constraints/fir_compiler_v7_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_fir_interpolation_0_0 || ORIG_REF_NAME==system_fir_interpolation_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_fir_interpolation_1_0/constraints/fir_compiler_v7_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_fir_interpolation_1_0 || ORIG_REF_NAME==system_fir_interpolation_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_fir_interpolation_2_0/constraints/fir_compiler_v7_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_fir_interpolation_2_0 || ORIG_REF_NAME==system_fir_interpolation_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_fir_interpolation_3_0/constraints/fir_compiler_v7_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_fir_interpolation_3_0 || ORIG_REF_NAME==system_fir_interpolation_3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/xilinx/common/up_clock_mon_constr.xdc
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==up_clock_mon || ORIG_REF_NAME==up_clock_mon} -quiet] -quiet

# XDC: bd/system/xilinx/common/up_xfer_status_constr.xdc
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==up_xfer_status || ORIG_REF_NAME==up_xfer_status} -quiet] -quiet

# XDC: bd/system/xilinx/common/ad_rst_constr.xdc
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ad_rst || ORIG_REF_NAME==ad_rst} -quiet] -quiet

# XDC: bd/system/xilinx/common/up_xfer_cntrl_constr.xdc
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==up_xfer_cntrl || ORIG_REF_NAME==up_xfer_cntrl} -quiet] -quiet

# XDC: bd/system/ip/system_axi_adrv9009_tx_dma_0/system_axi_adrv9009_tx_dma_0_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_adrv9009_tx_dma_0 || ORIG_REF_NAME==system_axi_adrv9009_tx_dma_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_adrv9009_dacfifo_0/system_axi_adrv9009_dacfifo_0_ooc.xdc

# XDC: bd/system/ip/system_axi_adrv9009_dacfifo_0/util_dacfifo_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_adrv9009_dacfifo_0 || ORIG_REF_NAME==system_axi_adrv9009_dacfifo_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/xilinx/common/up_clock_mon_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rx_axi_0 || ORIG_REF_NAME==system_rx_axi_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_rx_axi_0/system_rx_axi_0_ooc.xdc

# XDC: bd/system/ip/system_rx_axi_0/axi_jesd204_rx_constr.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rx_axi_0 || ORIG_REF_NAME==system_rx_axi_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_rx_0/system_rx_0_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rx_0 || ORIG_REF_NAME==system_rx_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/xilinx/common/up_clock_mon_constr.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==up_clock_mon || ORIG_REF_NAME==up_clock_mon} -quiet] -quiet

# XDC: bd/system/xilinx/common/up_xfer_status_constr.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==up_xfer_status || ORIG_REF_NAME==up_xfer_status} -quiet] -quiet

# XDC: bd/system/xilinx/common/ad_rst_constr.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ad_rst || ORIG_REF_NAME==ad_rst} -quiet] -quiet

# XDC: bd/system/xilinx/common/up_xfer_cntrl_constr.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==up_xfer_cntrl || ORIG_REF_NAME==up_xfer_cntrl} -quiet] -quiet

# XDC: bd/system/ip/system_fir_decimation_0_0/constraints/fir_compiler_v7_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_fir_decimation_0_0 || ORIG_REF_NAME==system_fir_decimation_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_fir_decimation_1_0/constraints/fir_compiler_v7_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_fir_decimation_1_0 || ORIG_REF_NAME==system_fir_decimation_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_fir_decimation_2_0/constraints/fir_compiler_v7_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_fir_decimation_2_0 || ORIG_REF_NAME==system_fir_decimation_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_fir_decimation_3_0/constraints/fir_compiler_v7_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_fir_decimation_3_0 || ORIG_REF_NAME==system_fir_decimation_3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_adrv9009_rx_dma_0/system_axi_adrv9009_rx_dma_0_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_adrv9009_rx_dma_0 || ORIG_REF_NAME==system_axi_adrv9009_rx_dma_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/xilinx/common/up_clock_mon_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rx_axi_1 || ORIG_REF_NAME==system_rx_axi_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_rx_axi_1/system_rx_axi_1_ooc.xdc

# XDC: bd/system/ip/system_rx_axi_1/axi_jesd204_rx_constr.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rx_axi_1 || ORIG_REF_NAME==system_rx_axi_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_rx_1/system_rx_1_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rx_1 || ORIG_REF_NAME==system_rx_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/xilinx/common/up_clock_mon_constr.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==up_clock_mon || ORIG_REF_NAME==up_clock_mon} -quiet] -quiet

# XDC: bd/system/xilinx/common/up_xfer_status_constr.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==up_xfer_status || ORIG_REF_NAME==up_xfer_status} -quiet] -quiet

# XDC: bd/system/xilinx/common/ad_rst_constr.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ad_rst || ORIG_REF_NAME==ad_rst} -quiet] -quiet

# XDC: bd/system/xilinx/common/up_xfer_cntrl_constr.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==up_xfer_cntrl || ORIG_REF_NAME==up_xfer_cntrl} -quiet] -quiet

# XDC: bd/system/ip/system_axi_adrv9009_rx_os_dma_0/system_axi_adrv9009_rx_os_dma_0_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_adrv9009_rx_os_dma_0 || ORIG_REF_NAME==system_axi_adrv9009_rx_os_dma_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_util_adrv9009_xcvr_0/util_adxcvr_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_util_adrv9009_xcvr_0 || ORIG_REF_NAME==system_util_adrv9009_xcvr_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_adrv9009_tx_device_clk_rstgen_0/system_adrv9009_tx_device_clk_rstgen_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_adrv9009_tx_device_clk_rstgen_0 || ORIG_REF_NAME==system_adrv9009_tx_device_clk_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_adrv9009_tx_device_clk_rstgen_0/system_adrv9009_tx_device_clk_rstgen_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_adrv9009_tx_device_clk_rstgen_0 || ORIG_REF_NAME==system_adrv9009_tx_device_clk_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_adrv9009_rx_device_clk_rstgen_0/system_adrv9009_rx_device_clk_rstgen_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_adrv9009_rx_device_clk_rstgen_0 || ORIG_REF_NAME==system_adrv9009_rx_device_clk_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_adrv9009_rx_device_clk_rstgen_0/system_adrv9009_rx_device_clk_rstgen_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_adrv9009_rx_device_clk_rstgen_0 || ORIG_REF_NAME==system_adrv9009_rx_device_clk_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_adrv9009_rx_os_device_clk_rstgen_0/system_adrv9009_rx_os_device_clk_rstgen_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_adrv9009_rx_os_device_clk_rstgen_0 || ORIG_REF_NAME==system_adrv9009_rx_os_device_clk_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_adrv9009_rx_os_device_clk_rstgen_0/system_adrv9009_rx_os_device_clk_rstgen_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_adrv9009_rx_os_device_clk_rstgen_0 || ORIG_REF_NAME==system_adrv9009_rx_os_device_clk_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_hp1_interconnect_0/ooc.xdc

# XDC: bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_1/bd_31bd_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_1/bd_31bd_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_5/bd_31bd_s00a2s_0_ooc.xdc

# XDC: bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_6/bd_31bd_sawn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_7/bd_31bd_swn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_8/bd_31bd_sbn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_9/bd_31bd_m00s2a_0_ooc.xdc

# XDC: bd/system/ip/system_axi_hp2_interconnect_0/ooc.xdc

# XDC: bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_1/bd_c0fd_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_1/bd_c0fd_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_5/bd_c0fd_s00a2s_0_ooc.xdc

# XDC: bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_6/bd_c0fd_sawn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_7/bd_c0fd_swn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_8/bd_c0fd_sbn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_9/bd_c0fd_m00s2a_0_ooc.xdc

# XDC: bd/system/ip/system_axi_hp3_interconnect_0/ooc.xdc

# XDC: bd/system/ip/system_axi_hp3_interconnect_0/bd_0/ip/ip_1/bd_503c_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/system/ip/system_axi_hp3_interconnect_0/bd_0/ip/ip_1/bd_503c_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/system/ip/system_axi_hp3_interconnect_0/bd_0/ip/ip_5/bd_503c_s00a2s_0_ooc.xdc

# XDC: bd/system/ip/system_axi_hp3_interconnect_0/bd_0/ip/ip_6/bd_503c_sarn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_hp3_interconnect_0/bd_0/ip/ip_7/bd_503c_srn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_hp3_interconnect_0/bd_0/ip/ip_8/bd_503c_m00s2a_0_ooc.xdc

# XDC: bd/system/ip/system_xbar_1/system_xbar_1_ooc.xdc

# XDC: bd/system/ip/system_jtag_axi_0_0/constraints/jtag_axi.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_jtag_axi_0_0 || ORIG_REF_NAME==system_jtag_axi_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_jtag_axi_0_0/system_jtag_axi_0_0_ooc.xdc

# XDC: bd/system/ip/system_tier2_xbar_0_0/system_tier2_xbar_0_0_ooc.xdc

# XDC: bd/system/ip/system_tier2_xbar_1_0/system_tier2_xbar_1_0_ooc.xdc

# XDC: bd/system/ip/system_tier2_xbar_2_0/system_tier2_xbar_2_0_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc

# XDC: bd/system/ip/system_s00_mmu_0/system_s00_mmu_0_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_2/system_auto_pc_2_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_3/system_auto_pc_3_ooc.xdc

# XDC: bd/system/ip/system_s01_mmu_0/system_s01_mmu_0_ooc.xdc

# XDC: bd/system/system_ooc.xdc
