# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config  -id {Vivado 12-1790}  -string {{Evaluation} {features} {should} {NOT} {be} {used} {in} {production} {systems.}}  -new_severity {WARNING} 
set_msg_config  -id {Place 30-73}  -string {{axi_spi}}  -new_severity {WARNING} 
set_msg_config  -string {{PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY}}  -new_severity {WARNING} 
set_msg_config  -id {BD 41-1343}  -new_severity {WARNING} 
set_msg_config  -id {BD 41-1306}  -new_severity {WARNING} 
set_msg_config  -id {BD 41-1276}  -severity {CRITICAL WARNING}  -new_severity {ERROR} 
set_msg_config  -id {IP_Flow 19-3656}  -new_severity {INFO} 
set_msg_config  -id {IP_Flow 19-4623}  -new_severity {INFO} 
set_msg_config  -id {IP_Flow 19-459}  -new_severity {INFO} 
set_msg_config  -id {Synth 8-3331}  -new_severity {INFO} 
set_msg_config  -id {Designutils 20-3303}  -string {{HDPYFinalizeIO}}  -new_severity {INFO} 
create_project -in_memory -part xczu9eg-ffvb1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.cache/wt [current_project]
set_property parent.project_path C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu102:part0:3.2 [current_project]
set_property ip_repo_paths {
  c:/github/hdl/library
  c:/github/ghdl/library
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/imports/hdl/library/util_fir_int/coefile_int.coe
read_verilog -library xil_defaultlib -sv {
  C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/imports/xvr_example/src_axi4/axi4_address_counter.sv
  C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/imports/xvr_example/src_axi4/axi4_bram_common_address.sv
  C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/imports/xvr_example/src_axi4/axi4_bram_common_address_fsm.sv
  C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/imports/xvr_example/src_axi4/axi4_burst_counter.sv
  C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/imports/xvr_example/src_axi4/axi4lite_slave_interface.sv
  C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/imports/xvr_example/src_axi4/axi4lite_slave_interface_read.sv
  C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/imports/xvr_example/src_axi4/axi4lite_slave_interface_read_fsm.sv
  C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/imports/xvr_example/src_axi4/axi4lite_slave_interface_write.sv
  C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/imports/xvr_example/src_axi4/axi4lite_slave_interface_write_fsm.sv
  C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/imports/xvr_example/src_axi4/axi4lite_to_drp_bridge.sv
  C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/imports/xvr_example/src_axi4/axi4lite_to_drp_bridge_counter.sv
  C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/imports/xvr_example/src_axi4/axi4lite_to_drp_bridge_fsm.sv
  C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/imports/xvr_example/src_axi4/bram_128k_x_32_and_32k_x_128.sv
  C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/imports/xvr_example/src_axi4/bram_32k_x_1.sv
  C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/imports/xvr_example/src_axi4/bram_32k_x_32.sv
  C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/imports/xvr_example/src_axi4/clock_counter.sv
  C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/imports/xvr_example/src/counter.sv
  C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/imports/xvr_example/src/xvr_awg.sv
  C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/imports/xvr_example/src/xvr_interface.sv
  C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/imports/xvr_example/src/xvr_refclk_out_interface.sv
  C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/imports/xvr_example/src/xvr_registers.sv
  C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/imports/xvr_example/src/xvr_rx_bram.sv
  C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/imports/xvr_example/src/xvr_rx_bram_fsm.sv
  C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/imports/xvr_example/src/xvr_tx_bram.sv
  C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/imports/xvr_example/src/xvr_tx_bram_fsm.sv
  C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/imports/hdl/projects/adrv9009/zcu102/system_top.v
}
read_verilog -library xil_defaultlib {
  C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/imports/hdl/library/util_cdc/sync_bits.v
  C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/imports/hdl/library/common/util_pulse_gen.v
  C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/imports/hdl/library/common/ad_bus_mux.v
  C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/imports/hdl/library/xilinx/common/ad_iobuf.v
  C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/hdl/system_wrapper.v
}
add_files C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_sys_ps8_0/system_sys_ps8_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_sys_ps8_0/system_sys_ps8_0.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_sys_250m_rstgen_0/system_sys_250m_rstgen_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_sys_250m_rstgen_0/system_sys_250m_rstgen_0.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_sys_500m_rstgen_0/system_sys_500m_rstgen_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_sys_500m_rstgen_0/system_sys_500m_rstgen_0.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_1/bd_a17c_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_1/bd_a17c_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_2/bd_a17c_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_3/bd_a17c_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_4/bd_a17c_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_5/bd_a17c_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_6/bd_a17c_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_10/bd_a17c_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_11/bd_a17c_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_12/bd_a17c_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_13/bd_a17c_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_14/bd_a17c_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_15/bd_a17c_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_19/bd_a17c_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_20/bd_a17c_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_21/bd_a17c_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_22/bd_a17c_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_23/bd_a17c_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_24/bd_a17c_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_25/bd_a17c_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_26/bd_a17c_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_27/bd_a17c_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_28/bd_a17c_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_29/bd_a17c_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_30/bd_a17c_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/xilinx/common/up_clock_mon_constr.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_tx_axi_0/system_tx_axi_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_tx_axi_0/axi_jesd204_tx_constr.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_tx_0/system_tx_0_constr.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_fir_interpolation_0_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_fir_interpolation_1_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_fir_interpolation_2_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_fir_interpolation_3_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/xilinx/common/up_clock_mon_constr.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/xilinx/common/up_xfer_status_constr.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/xilinx/common/ad_rst_constr.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/xilinx/common/up_xfer_cntrl_constr.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_adrv9009_tx_dma_0/system_axi_adrv9009_tx_dma_0_constr.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_adrv9009_dacfifo_0/system_axi_adrv9009_dacfifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_adrv9009_dacfifo_0/util_dacfifo_constr.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/xilinx/common/up_clock_mon_constr.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_rx_axi_0/system_rx_axi_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_rx_axi_0/axi_jesd204_rx_constr.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_rx_0/system_rx_0_constr.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/xilinx/common/up_clock_mon_constr.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/xilinx/common/up_xfer_status_constr.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/xilinx/common/ad_rst_constr.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/xilinx/common/up_xfer_cntrl_constr.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_fir_decimation_0_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_fir_decimation_1_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_fir_decimation_2_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_fir_decimation_3_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_adrv9009_rx_dma_0/system_axi_adrv9009_rx_dma_0_constr.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/xilinx/common/up_clock_mon_constr.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_rx_axi_1/system_rx_axi_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_rx_axi_1/axi_jesd204_rx_constr.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_rx_1/system_rx_1_constr.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/xilinx/common/up_clock_mon_constr.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/xilinx/common/up_xfer_status_constr.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/xilinx/common/ad_rst_constr.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/xilinx/common/up_xfer_cntrl_constr.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_adrv9009_rx_os_dma_0/system_axi_adrv9009_rx_os_dma_0_constr.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_util_adrv9009_xcvr_0/util_adxcvr_constr.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_adrv9009_tx_device_clk_rstgen_0/system_adrv9009_tx_device_clk_rstgen_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_adrv9009_tx_device_clk_rstgen_0/system_adrv9009_tx_device_clk_rstgen_0.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_adrv9009_rx_device_clk_rstgen_0/system_adrv9009_rx_device_clk_rstgen_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_adrv9009_rx_device_clk_rstgen_0/system_adrv9009_rx_device_clk_rstgen_0.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_adrv9009_rx_os_device_clk_rstgen_0/system_adrv9009_rx_os_device_clk_rstgen_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_adrv9009_rx_os_device_clk_rstgen_0/system_adrv9009_rx_os_device_clk_rstgen_0.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_1/bd_31bd_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_1/bd_31bd_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_5/bd_31bd_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_6/bd_31bd_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_7/bd_31bd_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_8/bd_31bd_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_9/bd_31bd_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_1/bd_c0fd_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_1/bd_c0fd_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_5/bd_c0fd_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_6/bd_c0fd_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_7/bd_c0fd_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_8/bd_c0fd_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_9/bd_c0fd_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp3_interconnect_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp3_interconnect_0/bd_0/ip/ip_1/bd_503c_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp3_interconnect_0/bd_0/ip/ip_1/bd_503c_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp3_interconnect_0/bd_0/ip/ip_5/bd_503c_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp3_interconnect_0/bd_0/ip/ip_6/bd_503c_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp3_interconnect_0/bd_0/ip/ip_7/bd_503c_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_axi_hp3_interconnect_0/bd_0/ip/ip_8/bd_503c_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_xbar_1/system_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_jtag_axi_0_0/constraints/jtag_axi.xdc]
set_property used_in_synthesis false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_jtag_axi_0_0/constraints/system_jtag_axi_0_0_impl.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_jtag_axi_0_0/constraints/system_jtag_axi_0_0_impl.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_jtag_axi_0_0/system_jtag_axi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_tier2_xbar_0_0/system_tier2_xbar_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_tier2_xbar_1_0/system_tier2_xbar_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_tier2_xbar_2_0/system_tier2_xbar_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_s00_mmu_0/system_s00_mmu_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_auto_pc_2/system_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_auto_pc_3/system_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/ip/system_s01_mmu_0/system_s01_mmu_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/bd/system/system_ooc.xdc]

read_ip -quiet c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/ip/xvr/xvr.xci
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/ip/xvr/synth/xvr_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/ip/xvr/synth/xvr.xdc]

read_ip -quiet c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/ip/xvr_refclk_out/xvr_refclk_out.xci
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/ip/xvr_refclk_out/synth/xvr_refclk_out_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/sources_1/ip/xvr_refclk_out/synth/xvr_refclk_out.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/constrs_1/imports/projects/common/xilinx/adi_fir_filter_constr.xdc
set_property used_in_implementation false [get_files C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/constrs_1/imports/projects/common/xilinx/adi_fir_filter_constr.xdc]

read_xdc C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/constrs_1/imports/projects/adrv9009/zcu102/system_constr.xdc
set_property used_in_implementation false [get_files C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/constrs_1/imports/projects/adrv9009/zcu102/system_constr.xdc]

read_xdc C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/constrs_1/imports/projects/common/zcu102/zcu102_system_constr.xdc
set_property used_in_implementation false [get_files C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/constrs_1/imports/projects/common/zcu102/zcu102_system_constr.xdc]

read_xdc C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/constrs_1/imports/zcu102/xvr_constraints.xdc
set_property used_in_implementation false [get_files C:/github/hdl/projects/adrv9009/zcu102/adrv9009_zcu102.srcs/constrs_1/imports/zcu102/xvr_constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top system_top -part xczu9eg-ffvb1156-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file system_top_utilization_synth.rpt -pb system_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
